[package]
name = "nukerus-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.99"
# wasm-pack = "0.13.1"


[lib]
crate-type = ["cdylib", "rlib"]  # ?? no clue what this shit is for
path = "./lib.rs"
